<?php

namespace backend\modules\book\models;

use Yii;

/**
 * @property integer $id
 * @property string $image
 * @property integer $book_id
 * @property integer $chapter_number
 * @property string $title
 * @property string $type
 * @property string $attachment
 * @property string $content
 * @property integer $is_active
 * @property string $created_date
 * @property string $modified_date
 */
class BookChapterBase extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public $tableName = 'book_chapter';

    public static function tableName()
    {
        return 'book_chapter';
    }

    public function afterDelete()
    {
        $id = $this->id;
        $uploadFolder = Yii::getAlias('@' . UPLOAD_DIR);

        $image_old = $this->image;
        if (strlen($image_old) > 0) {
            if (is_file($uploadFolder . '/book-chapter/' . $image_old)) {
                unlink($uploadFolder . '/book-chapter/' . $image_old);
            }
        }
        $attachment_old = $this->attachment;
        if (strlen($attachment_old) > 0) {
            if (is_file($uploadFolder . '/book-chapter/' . $attachment_old)) {
                unlink($uploadFolder . '/book-chapter/' . $attachment_old);
            }
        }

        $comments = BookComment::find()->where("chapter_id = $id")->all();
        foreach ($comments as $comment) {
            $comment->delete();
        }
        
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

}
